# Generated by Django 5.1.2 on 2026-07-24 20:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_livro_autores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Biblioteca', max_length=80, verbose_name='Nome da biblioteca')),
                ('subtitulo', models.CharField(blank=True, default='Sistema de Gestão', max_length=120, verbose_name='Subtítulo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo')),
                ('cor_primaria', models.CharField(default='#24425c', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Informe uma cor no formato #RRGGBB.')], verbose_name='Cor primária')),
                ('cor_destaque', models.CharField(default='#b7791f', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Informe uma cor no formato #RRGGBB.')], verbose_name='Cor de destaque')),
                ('cor_fundo', models.CharField(default='#eef0f2', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Informe uma cor no formato #RRGGBB.')], verbose_name='Cor de fundo')),
                ('mensagem_boas_vindas', models.TextField(blank=True, default='Explore o acervo, organize sua fila de leitura e acompanhe tudo na sua central do leitor.', verbose_name='Mensagem de boas-vindas')),
                ('rodape', models.CharField(blank=True, default='', max_length=200, verbose_name='Texto do rodapé')),
            ],
            options={
                'verbose_name': 'Configuração da biblioteca',
                'verbose_name_plural': 'Configuração da biblioteca',
            },
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo']},
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa (arquivo)'),
        ),
        migrations.AddField(
            model_name='livro',
            name='capa_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='Capa (URL)'),
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='livro',
            name='exemplares',
            field=models.PositiveIntegerField(default=1, verbose_name='Exemplares'),
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='livro',
            name='paginas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Páginas'),
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='livros', to='core.categoria'),
        ),
        migrations.CreateModel(
            name='InteracaoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('fila', 'Na fila'), ('lendo', 'Lendo'), ('lido', 'Lido')], max_length=10)),
                ('favorito', models.BooleanField(default=False)),
                ('avaliacao', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('resenha', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='core.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interação com livro',
                'verbose_name_plural': 'Interações com livros',
                'unique_together': {('usuario', 'livro')},
            },
        ),
    ]
