# Generated by Django 5.1.2 on 2026-07-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_configuracaobiblioteca_alter_autor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaobiblioteca',
            name='mensagem_boas_vindas',
            field=models.TextField(blank=True, default='Consulte o acervo, organize sua fila de leitura e acompanhe suas leituras.', verbose_name='Mensagem de boas-vindas'),
        ),
    ]
